data:
  img_shape: (128, 128)
  num_workers: 4

model:
  n_frames: 8
  n_feature_maps: 64
  feature_map_width: 32
  feature_map_height: 32
  feature_map_gauss_sigma: 1.5
  n_init_filters: 32
  n_convolutions_per_res: 1
  conv_kernel_size: 3
  decoder_hidden_activations: LeakyReLU
  encoder_hidden_activations: LeakyReLU
  weight_init: he_normal

training:
  k_folds: 0
  epochs: 200
  steps_per_epoch: 1000
  optim: AdamW
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_epoch_steps: 10
  lr_scheduler_gamma: 0.9
  initial_lr: 0.001
  max_lr: 0.001
  min_lr: 0.0001
  clip_norm: 1.0
  batch_size: 32
  l2_weight_decay: 5.0e-4
  reconstruction_loss: alexnet
  reconstruction_loss_scale: 1.0
  feature_map_regularization: 5.0
  separation_loss_scale: 0.1
  separation_loss_sigma: 0.02
  patchwise_contrastive_scale: 0.0
  patchwise_contrastive_starting_epoch: ...
  patchwise_contrastive_type: ...
  patchwise_contrastive_time_window: ...
  patchwise_contrastive_patch_size: ...
  patchwise_contrastive_alpha: ...
  use_emd: false
  emd_sum_scale: 1.0
  re_sample: false
  re_sample_scale: 0.02

validation:
  steps: 100
  freq: 25
  batch_size: 32
  save_video: true

evaluation:
  steps: -1

device: cuda:0
multi_gpu: false
log_dir: "results/ulosd_manipulator_new_128pix"
warm_start: false
warm_start_checkpoint: ''
warm_start_config: ''