data:
  num_workers: 4

model:
  n_frames: 4
  weight_init: he_normal
  conv:
    in_channels: 3
    hidden_sizes: [128, 64]  # [64, 32]
    out_channels: 8  # 8
    activation: ReLU
  spatial:
    temperature: 0.1
    normalize: True
  fc:
    in_features: 16  # 16
    out_img_width: 40  # 60
    out_img_height: 40  # 60
    activation: Sigmoid  # ReLu?

training:
  optim: Adam
  k_folds: 0
  epochs: 500
  steps_per_epoch: 1000  # 1000
  initial_lr: 0.001
  l2_weight_decay: 0.0005
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_gamma: 0.75
  lr_scheduler_epoch_steps: 10
  batch_size: 8
  smoothness_penalty: True
  save_grad_flow_plot: True

evaluation:
  batch_size: 1
  chckpt_path: ""

validation:
  freq: 5
  steps: 50
  batch_size: 8
  save_plot: True


device: "cuda:0"
warm_start: False
log_dir: "results/dsae_manipulator_new_128pix"