conv:
  in_channels: 3
  hidden_sizes: [128, 64]
  out_channels: 16
  activation: "ReLU"

spatial:
  temperature: 0.9
  normalize: False

fc:
  in_features: 32
  out_img_width: 60
  out_img_height: 60
  activation: "Sigmoid"

training:
  epochs: 100
  lr: 0.0005
  weight_decay: 0.0001
  batch_size: 1
  smoothness_penalty: True

evaluation:
  batch_size: 1
  chckpt_path: "results/dsae/2021_4_28_17_43/checkpoints/chckpt_e15.PTH"

validation:
  freq: 1
  val_split: 0.8

device: "cuda:0"
log_dir: "results/dsae/"