conv:
  in_channels: 3
  hidden_sizes: [64, 32]
  out_channels: 16
  activation: "ReLU"

spatial:
  temperature: 0.9
  normalize: False

fc:
  in_features: 32
  out_img_width: 60
  out_img_height: 60
  activation: "Sigmoid"

training:
  k_folds: 3
  epochs: 100
  lr: 0.0005
  weight_decay: 0.0001
  batch_size: 8
  smoothness_penalty: True

evaluation:
  batch_size: 1
  chckpt_path: "results/dsae/2021_5_19_11_47/checkpoints/chckpt_e32.PTH"

validation:
  freq: 2
  val_split: 0.1

device: "cpu"
log_dir: "results/dsae/"