model:
  n_frames: 5
  n_convolutions: 3
  channels: (3, 256, 128, 64)
  channels_3d: 16
  n_fc_layers: 3
  fc_layer_dims: (256, 256, 32)

training:
  k_folds: 5
  epochs: 50
  batch_size: 1


validation:

evaluation:

device: "cuda:0"
log_dir: "results/mf_tcn"