data:
  tasks: 'stir'
  overlap: 0
  img_scale_factor: 0.25

model:
  inception_url: 'https://download.pytorch.org/models/inception_v3_google-0cc3c7bd.pth'
  n_frames: 9
  positive_range: 2
  n_views: 1
  n_convolutions: 2
  conv_channels: (288, 128, 64)
  embedding_size: 32

training:
  epochs: 50
  k_folds: 5
  batch_size: 4
  lr: 0.0001

validation:
  freq: 1

evaluation:

device: "cuda:0"
log_dir: "results/tcn"