data:
  num_workers: 0
  img_shape: (3, 64, 64)

model:
  n_frames: 3
  num_img_channels: 3
  num_keypoints: 2
  activation: 'prelu'
  gaussian_map_std: 0.05
  weight_init: 'xavier_uniform'
  skip_connections: False

training:
  epochs: 100
  steps_per_epoch: 100  # 100
  optim: 'adam'
  k_folds: 1
  initial_lr: 0.0001
  lr_scheduler: 'StepLR'
  lr_scheduler_epoch_steps: 30
  batch_size: 64  # 128
  loss_function: 'mse'
  l2_weight_decay: 0.000000

validation:
  freq: 5
  batch_size: 64  # 128
  save_grad_plots: True
  save_eval_examples: True

evaluation:

device: 'cuda:0'
log_dir: 'results/transporter'
warm_start: False