model:
  q:
    hidden_size: 128
    num_layers: 8
    num_heads: 2
  pi:
    hidden_size: 128
    num_layers: 8
    num_heads: 1
  eta:
    hidden_size: 128
    num_layers: 8
    num_heads: 2
  num_latent_vars: 64
  num_actions: ...
  num_states: ...

training:
  lr: 0.0001
  epsilon_init: 0.3
  epsilon_final: 0.05
  epsilon_decay_episodes: 30
  option_lh_weight: 1.0
  DKL_weight: 0.01

validation:

evaluation:

device: 'cuda:0'