data:
  img_shape: (64, 64)
  num_workers: 4

model:
  n_frames: 8  # 8
  n_feature_maps: 48  # 48
  feature_map_width: 16
  feature_map_height: 16
  feature_map_gauss_sigma: 1.5  # 'keypoint_width' in keras code
  n_init_filters: 16  # Latent code size?
  n_convolutions_per_res: 2  # 'layers_per_scale' in the keras code
  conv_kernel_size: 3
  decoder_hidden_activations: LeakyReLU # LeakyReLU
  encoder_hidden_activations: LeakyReLU  # LeakyReLU
  weight_init: he_uniform

training:
  k_folds: 0
  epochs: 100
  steps_per_epoch: 100  # 100
  optim: 'AdamW'
  l2_weight_decay: 0.0001
  lr_scheduler: 'StepLR'
  lr_scheduler_epoch_steps: 30
  initial_lr: 0.001
  min_lr: 0.0001
  clip_norm: 10
  batch_size: 32  # 32
  feature_map_regularization: 0.01  # 0.01  (Key-point sparsity scale)
  reconstruction_loss: mse  # alexnet  # mse
  reconstruction_loss_scale: 1.0
  separation_loss_scale: 0.02  # 0.02
  separation_loss_sigma: 0.002  # 0.002
  consistency_loss_scale: 0.0
  tc_loss_scale: 0.0
  pixelwise_contrastive_scale: 0.0

validation:
  steps: 100
  freq: 3
  batch_size: 32  # 32
  save_video: true

evaluation:
  steps: -1

device: 'cuda:0'
multi_gpu: false
log_dir: "results/ulosd_human36m"
warm_start: false
warm_start_checkpoint: ''
warm_start_config: ''