data:
  tasks: ['stir', 'pour', 'pass', 'place_in_box']
  timesteps_per_sample: 8
  overlap: 3
  img_scale_factors: (160/240, 160/640)
  num_workers: 4

model:
  n_frames: 8
  n_feature_maps: 64
  feature_map_width: 20
  feature_map_height: 20
  feature_map_regularization: 5.0
  n_init_filters: 32
  n_convolutions_per_res: 2
  conv_kernel_size: 3
  conv_kernel_regularization: 1e-4
  conv_init: 'he_uniform'
  dense_init: 'he_uniform'

training:
  k_folds: 3
  epochs: 100
  steps_per_epoch: 100  # 100
  lr: 0.001
  clip_norm: 10
  batch_size: 32  # 32
  separation_loss_scale: 10.0
  separation_loss_sigma: 0.1

validation:
  freq: 5
  batch_size: 32

evaluation:

device: 'cuda:0'
log_dir: "results/ulosd"