data:
  img_shape: (64, 64)
  num_workers: 0

device: cuda:0
evaluation: null
log_dir: results/ulosd/
model:
  conv_init: he_uniform
  conv_kernel_size: 3
  decoder_hidden_activations: prelu
  dense_init: he_uniform
  encoder_hidden_activations: prelu
  feature_map_height: 16
  feature_map_width: 16
  inception_url: https://download.pytorch.org/models/inception_v3_google-0cc3c7bd.pth
  n_convolutions_per_res: 3
  n_feature_maps: 32
  n_frames: 16
  n_init_filters: 32
multi_gpu: true
training:
  batch_size: 16
  clip_norm: 10
  epochs: 200
  feature_map_regularization: 0.5
  initial_lr: 0.00005
  k_folds: 1
  l2_weight_decay: 0.0005
  lr_scheduler: None
  lr_scheduler_epoch_steps: 30
  min_lr: 0.0001
  optim: Adam
  reconstruction_loss: 'inception'
  separation_loss_scale: 5.0
  separation_loss_sigma: 0.2
  steps_per_epoch: 200
used_gpus: '[''Tesla V100-PCIE-32GB'']'
validation:
  batch_size: 16
  freq: 5
  save_video: true
warm_start: false
warm_start_checkpoint: ''
warm_start_config: ''
