data:
  img_shape: (64, 64)
  num_workers: 0

device: cuda:0
evaluation: null
log_dir: results/ulosd/
model:
  conv_init: he_uniform
  conv_kernel_size: 3  # 3
  decoder_hidden_activations: LeakyReLU
  dense_init: he_uniform
  encoder_hidden_activations: LeakyReLU
  feature_map_height: 16
  feature_map_width: 16
  inception_url: https://download.pytorch.org/models/inception_v3_google-0cc3c7bd.pth
  n_convolutions_per_res: 2  # 2
  n_feature_maps: 4  # 64
  n_frames: 4
  n_init_filters: 64  # 32
multi_gpu: true
training:
  batch_size: 16  # 32
  clip_norm: 10  # 10
  epochs: 100
  feature_map_regularization: 5.0  # 5.0
  initial_lr: 0.0005  # 0.001
  k_folds: 1
  l2_weight_decay: 0.0001  # 0.0001
  lr_scheduler: StepLR
  lr_scheduler_epoch_steps: 50
  min_lr: 0.0001
  optim: Adam
  reconstruction_loss: 'mse'  # mse
  separation_loss_scale: 10.0  # 10
  separation_loss_sigma: 0.1  # 0.1
  steps_per_epoch: 100  # 100
used_gpus: '[''Tesla V100-PCIE-32GB'']'
validation:
  batch_size: 16
  freq: 5
  save_video: true
warm_start: false
warm_start_checkpoint: ''
warm_start_config: ''
