data:
  img_shape: (64, 64)
  num_workers: 4

model:
  n_frames: 8
  n_feature_maps: 64
  feature_map_width: 16
  feature_map_height: 16
  feature_map_gauss_sigma: 1.5  # 'keypoint_width' in keras code
  n_init_filters: 32
  n_convolutions_per_res: 4  # 'layers_per_scale' in the keras code
  conv_kernel_size: 3
  conv_kernel_regularization: 1e-4  # This can be removed?
  decoder_hidden_activations: prelu  # LeakyReLU
  encoder_hidden_activations: prelu  # LeakyReLU
  weight_init: he_uniform

training:
  k_folds: 0
  epochs: 200
  steps_per_epoch: 100  # 100
  optim: 'AdamW'
  l2_weight_decay: 0.000005
  feature_map_regularization: 5.0
  lr_scheduler: 'StepLR'
  lr_scheduler_epoch_steps: 60
  initial_lr: 0.00005
  min_lr: 0.0001
  clip_norm: 10
  batch_size: 4 # 32
  reconstruction_loss: 'sse'
  reconstruction_loss_scale: 1.0
  separation_loss_scale: 10.0
  separation_loss_sigma: 0.1
  consistency_loss_scale: 0.0  # Set to 0 to not use this loss
  tc_loss_alpha: 5.0
  tc_loss_scale: 0.0
  pixelwise_contrastive_scale: 100.0
  pixelwise_contrastive_patch_size: (11, 11)
  pixelwise_contrastive_time_window: 7
  pixelwise_contrastive_alpha: 0.5

validation:
  steps: 10
  freq: 5
  batch_size: 1  # 32
  save_video: true

evaluation:
  steps: -1

device: 'cuda:0'
multi_gpu: false
log_dir: "results/ulosd_acrobot_pixelwise_contrastive"
warm_start: false
warm_start_checkpoint: ''
warm_start_config: ''