data:
  img_shape: (64, 64)
  num_workers: 0

model:
  n_frames: 16
  n_feature_maps: 64
  feature_map_width: 16
  feature_map_height: 16
  feature_map_gauss_sigma: 1.5  # 'keypoint_width' in keras code
  n_init_filters: 32
  n_convolutions_per_res: 2  # 'layers_per_scale' in the keras code
  conv_kernel_size: 3
  conv_kernel_regularization: 1e-4  # This can be removed?
  decoder_hidden_activations: prelu  # LeakyReLU
  encoder_hidden_activations: prelu  # LeakyReLU
  weight_init: he_uniform

training:
  k_folds: 0
  epochs: 100
  steps_per_epoch: 200  # 100
  optim: 'AdamW'
  l2_weight_decay: 0.000005
  feature_map_regularization: 5.0
  lr_scheduler: 'StepLR'
  lr_scheduler_epoch_steps: 30
  initial_lr: 0.00005
  min_lr: 0.0001
  clip_norm: 10
  batch_size: 4 # 32
  reconstruction_loss: 'sse'
  separation_loss_scale: 10.0
  separation_loss_sigma: 0.1
  consistency_loss_scale: 10.0  # Set to 0 to not use this loss

validation:
  steps: -1
  freq: 3
  batch_size: 4  # 32
  save_video: true

evaluation:
  steps: -1

device: 'cuda:0'
multi_gpu: false
log_dir: "results/ulosd"
warm_start: false
warm_start_checkpoint: ''
warm_start_config: ''