data:
  tasks: ['stir', 'pour', 'pass', 'stack', 'place_in_box']
  timesteps_per_sample: 8
  overlap: 3
  img_shape: (160, 160)
  num_workers: 4

model:
  n_frames: 16
  n_feature_maps: 32
  feature_map_width: 20
  feature_map_height: 20
  n_init_filters: 32
  n_convolutions_per_res: 3
  conv_kernel_size: 3
  encoder_hidden_activations: 'prelu'
  decoder_hidden_activations: 'prelu'
  conv_init: 'he_uniform'
  dense_init: 'he_uniform'
  inception_url: 'https://download.pytorch.org/models/inception_v3_google-0cc3c7bd.pth'

training:
  k_folds: 1
  epochs: 100
  steps_per_epoch: 100  # 100
  optim: 'Adam'
  l2_weight_decay: 0.0001
  feature_map_regularization: 0.1
  lr_scheduler: 'StepLR'
  lr_scheduler_epoch_steps: 30
  initial_lr: 0.0001
  min_lr: 0.0001
  clip_norm: 10
  batch_size: 32  # 32
  reconstruction_loss: 'inception'
  separation_loss_scale: 2.0
  separation_loss_sigma: 0.02

validation:
  freq: 5
  batch_size: 32  # 32
  save_video: True

evaluation:

device: 'cuda:0'
multi_gpu: True
warm_start: False
warm_start_config: ''
warm_start_checkpoint: ''
log_dir: "results/ulosd"