data:
  num_workers: 4
  img_shape: (3, 128, 128)

model:
  n_frames: 4
  hidden_dim: 32
  num_img_channels: 3
  num_keypoints: 64
  activation: LeakyReLU
  gaussian_map_std: 0.15
  weight_init: he_normal
  skip_connections: False

training:
  epochs: 1000
  steps_per_epoch: 500
  optim: AdamW
  k_folds: 1
  initial_lr: 0.01
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_epoch_steps: 10
  lr_scheduler_gamma: 0.9
  batch_size: 64
  loss_function: mse
  l2_weight_decay: 0.0005
  grad_clip_max_norm: 5.0

validation:
  steps: -1
  freq: 5
  batch_size: 4
  save_grad_plots: True
  save_eval_examples: True

evaluation:

device: cuda:0
log_dir: 'results/transporter_human36m_new_128pix'
warm_start: False