data:
  num_workers: 0

model:
  n_frames: 4
  weight_init: he_uniform
  conv:
    in_channels: 3
    hidden_sizes: [64, 32]  # [64, 32]
    out_channels: 16  # 8
    activation: LeakyReLU
  spatial:
    temperature: 0.9
    normalize: True
  fc:
    in_features: 32  # 16
    out_img_width: 60  # 60
    out_img_height: 60  # 60
    activation: ReLU  # ReLu?

training:
  optim: Adam
  k_folds: 0
  epochs: 500
  steps_per_epoch: 1000
  initial_lr: 0.0001
  l2_weight_decay: 0.00005
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_gamma: 0.75
  lr_scheduler_epoch_steps: 10
  batch_size: 4
  smoothness_penalty: False
  save_grad_flow_plot: True

evaluation:
  batch_size: 1
  chckpt_path: ""

validation:
  freq: 5
  steps: 50
  batch_size: 4
  save_plot: True


device: "cuda:0"
warm_start: False
log_dir: "results/dsae"