data:
  num_workers: 4
  img_shape: (3, 256, 256)

model:
  n_frames: 3  # Len. of sequence to sample. First sample is used as source frame, last as target frame
  hidden_dim: 32  # 128??
  num_img_channels: 3
  num_keypoints: 9
  activation: LeakyReLU
  gaussian_map_std: 0.05
  weight_init: he_normal
  skip_connections: False

training:
  epochs: 200
  steps_per_epoch: 100  # 100
  optim: AdamW
  k_folds: 1
  initial_lr: 0.1
  lr_scheduler: StepLR
  lr_scheduler_epoch_steps: 30
  lr_scheduler_gamma: 0.5
  batch_size: 16  # 32
  loss_function: alexnet  # inception
  l2_weight_decay: 0.0005
  grad_clip_max_norm: 5.0

validation:
  steps: -1  # 100
  freq: 5
  batch_size: 16  # 32
  save_grad_plots: True
  save_eval_examples: False

evaluation:

device: cuda:0  # cuda:0
log_dir: 'results/transporter_human36m'
warm_start: False