data:
  num_workers: 4
  img_shape: (3, 128, 128)

model:
  n_frames: 10  # Len. of sequence to sample. First sample is used as source frame, last as target frame
  hidden_dim: 32  # 128??
  num_img_channels: 3
  num_keypoints: 6
  activation: prelu
  gaussian_map_std: 0.15
  weight_init: he_normal
  skip_connections: False

training:
  epochs: 100
  steps_per_epoch: 500
  optim: Adam
  k_folds: 0
  initial_lr: 0.01
  lr_scheduler: StepLR
  lr_scheduler_epoch_steps: 30
  lr_scheduler_gamma: 0.5
  batch_size: 64
  loss_function: alexnet
  l2_weight_decay: 0.0000001
  grad_clip_max_norm: 5.0

validation:
  steps: -1
  freq: 5
  batch_size: 4
  save_grad_plots: True
  save_eval_examples: True

evaluation:

device: cuda:0  # cuda:0
log_dir: 'results/transporter_human36m_new_128pix'
warm_start: False