conv:
  in_channels: 3
  hidden_sizes: [64, 32]
  out_channels: 16
  activation: "ReLU"

spatial:
  temperature: 0.9
  normalize: False

fc:
  in_features: 32
  out_img_width: 60
  out_img_height: 60
  activation: "Sigmoid"

training:
  epochs: 100
  lr: 0.001
  smoothness_penalty: False

evaluation: