data:
  img_shape: (64, 64)
  num_workers: 4

model:
  n_frames: 8  # 8
  n_feature_maps: 4 # 64
  feature_map_width: 16  # 16
  feature_map_height: 16  # 16
  feature_map_gauss_sigma: 1.0  # 'keypoint_width' in keras code
  n_init_filters: 32  # 128
  n_convolutions_per_res: 4  # 1 'layers_per_scale' in the keras code
  conv_kernel_size: 3
  decoder_hidden_activations: LeakyReLU  # LeakyReLU
  encoder_hidden_activations: LeakyReLU  # LeakyReLU
  weight_init: he_uniform

training:
  k_folds: 0
  epochs: 100
  steps_per_epoch: 100  # 100
  optim: AdamW
  lr_scheduler: StepLR  # StepLR
  lr_scheduler_epoch_steps: 30
  initial_lr: 1.0e-04
  min_lr: 0.001
  clip_norm: 5.0
  batch_size: 4 # 32
  l2_weight_decay: 0.00001
  reconstruction_loss: sse
  reconstruction_loss_scale: 0.1  # 1.0
  feature_map_regularization: 1.0  # 5.0
  separation_loss_scale: 0.0  # 10.0
  separation_loss_sigma: 0.1
  consistency_loss_scale: 0.0  # Set to 0 to not use this loss
  tc_loss_scale: 0.0  # Set to 0 to not use this loss
  pixelwise_contrastive_type: fmap
  pixelwise_contrastive_scale: 10.0
  pixelwise_contrastive_time_window: 7  # 5
  pixelwise_contrastive_patch_size: (7, 7)
  pixelwise_contrastive_alpha: 1.0

validation:
  steps: 50
  freq: 5
  batch_size: 4  # 32
  save_video: true

evaluation:
  steps: -1

device: 'cuda:0'
multi_gpu: false
log_dir: "results/ulosd_acrobot"
warm_start: false
warm_start_checkpoint: ''
warm_start_config: ''