data:
  img_shape: (64, 64)
  num_workers: 4

model:
  n_frames: 8  # 8
  n_feature_maps: 64  # 64
  feature_map_width: 16  # 16
  feature_map_height: 16  # 16
  feature_map_gauss_sigma: 1.5  # 'keypoint_width' in keras code
  n_init_filters: 128  # 128
  n_convolutions_per_res: 1  # 1 'layers_per_scale' in the keras code
  conv_kernel_size: 3
  decoder_hidden_activations: LeakyReLU  # prelu
  encoder_hidden_activations: LeakyReLU  # prelu
  weight_init: he_uniform

training:
  k_folds: 1
  epochs: 1000  # 200
  steps_per_epoch: 100  # 200
  optim: Adam
  lr_scheduler: StepLR  # StepLR
  lr_scheduler_epoch_steps: 300
  lr_scheduler_gamma: 0.5
  initial_lr: 0.001
  max_lr: 0.001
  min_lr: 0.0001
  clip_norm: 5.0
  batch_size: 32  # 32
  l2_weight_decay: 1.0e-4  # 1.0e-6
  reconstruction_loss: mse  # sse / mse / inception / alexnet
  reconstruction_loss_scale: 1.0  # 1.0
  feature_map_regularization: 5.0  # 5.0
  separation_loss_scale: 0.1  # 10.0 for sse reconstruction loss, 0.1 for mse
  separation_loss_sigma: 0.02  # 0.02? 0.05?
  patchwise_contrastive_starting_epoch: 0
  patchwise_contrastive_type: patch
  patchwise_contrastive_scale: 0.0
  patchwise_contrastive_time_window: 1  # 5
  patchwise_contrastive_patch_size: (9, 9)
  patchwise_contrastive_alpha: 1.0  # 0.1
  use_emd: false
  emd_sum_scale: 1.0
  re_sample: false
  re_sample_scale: 0.02

validation:
  steps: 100
  freq: 50
  batch_size: 32  # 32
  save_video: true

evaluation:
  steps: -1

device: cuda:0
multi_gpu: false
log_dir: "results/ulosd_manipulator_vanilla"
warm_start: false
warm_start_checkpoint: ''
warm_start_config: ''