data:
  img_shape: (128, 128)
  num_workers: 0

model:
  n_frames: 8
  n_feature_maps: 64  # 64
  feature_map_width: 16
  feature_map_height: 16
  feature_map_gauss_sigma: 1.5  # 'keypoint_width' in keras code
  n_init_filters: 128  # 128
  n_convolutions_per_res: 2  # 'layers_per_scale' in the keras code
  conv_kernel_size: 3
  decoder_hidden_activations: prelu  # LeakyReLU
  encoder_hidden_activations: prelu  # LeakyReLU
  weight_init: he_uniform

training:
  k_folds: 0
  epochs: 500
  steps_per_epoch: 20  # 100
  optim: 'AdamW'
  lr_scheduler: 'StepLR'
  lr_scheduler_epoch_steps: 30  # 30
  initial_lr: 0.001
  min_lr: 0.0001
  clip_norm: 10
  batch_size: 2  # 32
  l2_weight_decay: 0.0001
  reconstruction_loss: 'sse'
  reconstruction_loss_scale: 0.01
  feature_map_regularization: 5.0  # Key-point sparsity scale
  separation_loss_scale: 0.1  # 0.1
  separation_loss_sigma: 0.02  # 0.02
  consistency_loss_scale: 0.0  # Set to 0 to not use this loss
  tc_loss_scale: 0.0
  pixelwise_contrastive_scale: 0.0
  pixelwise_contrastive_time_window: 3
  pixelwise_contrastive_alpha: 1.0

validation:
  steps: 20
  freq: 5
  batch_size: 2  # 32
  save_video: true

evaluation:
  steps: -1

device: 'cuda:0'
multi_gpu: false
log_dir: "results/ulosd_dmcs"
warm_start: false
warm_start_checkpoint: ''
warm_start_config: ''