data:
  img_shape: (64, 64)
  num_workers: 4

model:
  n_frames: 8  # 16
  n_feature_maps: 64
  feature_map_width: 32
  feature_map_height: 32
  feature_map_gauss_sigma: 1.5  # 'keypoint_width' in keras code
  n_init_filters: 128
  n_convolutions_per_res: 4  # 'layers_per_scale' in the keras code
  conv_kernel_size: 3
  conv_kernel_regularization: 1e-4  # This can be removed?
  decoder_hidden_activations: prelu
  encoder_hidden_activations: prelu
  weight_init: he_uniform

training:
  k_folds: 0
  epochs: 200
  steps_per_epoch: 100  # 100
  optim: 'AdamW'
  l2_weight_decay: 0.00001
  feature_map_regularization: 5.0
  lr_scheduler: 'StepLR'
  lr_scheduler_epoch_steps: 50
  initial_lr: 0.00005
  min_lr: 0.0001
  clip_norm: 2
  batch_size: 4  # 32
  reconstruction_loss: 'alexnet'  # 'sse'
  separation_loss_scale: 10.0
  separation_loss_sigma: 0.1
  consistency_loss_scale: 0.0
  tc_loss_alpha: 5
  tc_loss_scale: 0.1

validation:
  steps: 100
  freq: 3
  batch_size: 4  # 32
  save_video: true

evaluation:
  steps: -1

device: 'cuda:0'
multi_gpu: false
log_dir: "results/ulosd_mime_tc_triplet"
warm_start: false
warm_start_checkpoint: ''
warm_start_config: ''