data:
  img_shape: (64, 64)
  num_workers: 4

model:
  n_frames: 8  # 8
  n_feature_maps: 64  # 64
  feature_map_width: 16  # 16
  feature_map_height: 16  # 16
  feature_map_gauss_sigma: 1.5  # 'keypoint_width' in keras code
  n_init_filters: 32  # 128
  n_convolutions_per_res: 2  # 1 'layers_per_scale' in the keras code
  conv_kernel_size: 3
  decoder_hidden_activations: prelu  # prelu
  encoder_hidden_activations: prelu  # prelu
  weight_init: he_uniform

training:
  k_folds: 0
  epochs: 200
  steps_per_epoch: 100  # 200
  optim: AdamW
  lr_scheduler: StepLR  # StepLR
  lr_scheduler_epoch_steps: 30
  initial_lr: 5.0e-05
  max_lr: 0.001
  min_lr: 0.001
  clip_norm: 5.0
  batch_size: 4 # 32
  l2_weight_decay: 1.0e-9
  reconstruction_loss: sse  # sse / mse
  reconstruction_loss_scale: 1.0  # 1.0
  feature_map_regularization: 5.0  # 5.0
  separation_loss_scale: 10.0  # 10.0 for sse reconstruction loss, 0.1 for mse
  separation_loss_sigma: 0.1  # 0.02?
  consistency_loss_scale: 0.0  # Set to 0 to not use this loss
  tc_loss_scale: 0.0  # Set to 0 to not use this loss
  pixelwise_contrastive_starting_epoch: 50
  pixelwise_contrastive_type: patch
  pixelwise_contrastive_scale: 1.0
  pixelwise_contrastive_time_window: 7  # 5
  pixelwise_contrastive_patch_size: (7, 7)
  pixelwise_contrastive_alpha: 0.1
  use_emd: false
  emd_sum_scale: 1.0
  re_sample: true
  re_sample_scale: 0.05

validation:
  steps: 100
  freq: 5
  batch_size: 4  # 32
  save_video: true

evaluation:
  steps: -1

device: 'cuda:0'
multi_gpu: false
log_dir: "results/ulosd_acrobot"
warm_start: false
warm_start_checkpoint: ''
warm_start_config: ''