data:
  img_shape: (64, 64)
  num_workers: 4

model:
  n_frames: 8  # 8
  n_feature_maps: 32  # 64
  feature_map_width: 16  # 16
  feature_map_height: 16  # 16
  feature_map_gauss_sigma: 1.5  # 'keypoint_width' in keras code
  n_init_filters: 128  # 128
  n_convolutions_per_res: 3  # 1 'layers_per_scale' in the keras code
  conv_kernel_size: 3
  decoder_hidden_activations: prelu  # LeakyReLU
  encoder_hidden_activations: prelu  # LeakyReLU
  weight_init: he_uniform

training:
  k_folds: 0
  epochs: 200
  steps_per_epoch: 200  # 200
  optim: AdamW
  lr_scheduler: StepLR  # StepLR
  lr_scheduler_epoch_steps: 50
  initial_lr: 1.0e-03
  min_lr: 0.001
  clip_norm: 2.0
  batch_size: 4 # 32
  l2_weight_decay: 5.0e-7
  reconstruction_loss: sse
  reconstruction_loss_scale: 1.0  # 1.0
  feature_map_regularization: 5.0  # 5.0
  separation_loss_scale: 10.0  # 10.0
  separation_loss_sigma: 0.1
  consistency_loss_scale: 0.0  # Set to 0 to not use this loss
  tc_loss_scale: 0.0  # Set to 0 to not use this loss
  pixelwise_contrastive_starting_epoch: 50
  pixelwise_contrastive_type: patch
  pixelwise_contrastive_scale: 1.0
  pixelwise_contrastive_time_window: 5  # 5
  pixelwise_contrastive_patch_size: (5, 5)
  pixelwise_contrastive_alpha: 1.0

validation:
  steps: 50
  freq: 5
  batch_size: 4  # 32
  save_video: true

evaluation:
  steps: -1

device: 'cuda:0'
multi_gpu: false
log_dir: "results/ulosd_acrobot"
warm_start: false
warm_start_checkpoint: ''
warm_start_config: ''