data:
  num_workers: 4
  img_shape: (3, 64, 64)

model:
  n_frames: 4  # Len. of sequence to sample. First sample is used as source frame, random other as target frame
  num_img_channels: 3
  hidden_dim: 32
  num_keypoints: 3  # 2/3/4
  activation: LeakyReLU  # LeakyReLU
  gaussian_map_std: 0.15  # 0.15
  weight_init: he_normal
  skip_connections: False

training:
  epochs: 200
  steps_per_epoch: 100
  optim: AdamW
  k_folds: 1  # -1 Uses the whole set for both, training and validation, while 1 splits it into (90% training, 10%val)
  initial_lr: 0.01
  lr_scheduler: StepLR
  lr_scheduler_epoch_steps: 30
  lr_scheduler_gamma: 0.5
  batch_size: 64
  loss_function: mse
  l2_weight_decay: 0.0005
  grad_clip_max_norm: 5.0

validation:
  steps: -1
  freq: 5
  batch_size: 4
  save_grad_plots: False  # Set false to reduce memory load and increase speed
  save_eval_examples: False  # Set false to reduce memory load and increase speed

evaluation:

device: cuda:0  # cuda:0
log_dir: 'results/transporter_acrobot_new_64pix'
warm_start: False