data:
  num_workers: 4
  img_shape: (3, 64, 64)

model:
  n_frames: 4  # Len. of sequence to sample. First sample is used as source frame, last as target frame
  hidden_dim: 32
  num_img_channels: 3
  num_keypoints: 7  # 6 ?
  activation: LeakyReLU
  gaussian_map_std: 0.15
  weight_init: he_normal
  skip_connections: False

training:
  epochs: 200
  steps_per_epoch: 100  # 100
  optim: AdamW
  k_folds: 1
  initial_lr: 0.01
  lr_scheduler: StepLR
  lr_scheduler_epoch_steps: 30
  lr_scheduler_gamma: 0.5
  batch_size: 64  # 128
  loss_function: mse  # sse, mse, inception, alexnet
  l2_weight_decay: 0.0005
  grad_clip_max_norm: 5.0

validation:
  steps: -1  # 100
  freq: 5
  batch_size: 4  # 128
  save_grad_plots: True
  save_eval_examples: True

evaluation:

device: cuda:0  # cuda:0
log_dir: 'results/transporter_walker'
warm_start: False