data:
  img_shape: (128, 128)
  num_workers: 4

model:
  n_frames: 8
  n_feature_maps: 48
  feature_map_width: 32  # 64
  feature_map_height: 32  # 64
  feature_map_gauss_sigma: 1.5
  n_init_filters: 32
  n_convolutions_per_res: 1  # 2
  conv_kernel_size: 3
  decoder_hidden_activations: prelu
  encoder_hidden_activations: prelu
  weight_init: he_normal

training:
  k_folds: 0  # 1
  epochs: 100
  steps_per_epoch: 500
  optim: Adam
  lr_scheduler: StepLR
  lr_scheduler_epoch_steps: 30
  lr_scheduler_gamma: 0.5
  initial_lr: 0.0001
  max_lr: 0.001
  min_lr: 0.0001
  clip_norm: 5.0
  batch_size: 8
  l2_weight_decay: 0.0000001
  reconstruction_loss: alexnet
  reconstruction_loss_scale: 1.0
  feature_map_regularization: 0.1
  separation_loss_scale: 0.02
  separation_loss_sigma: 0.002
  patchwise_contrastive_scale: 0.0
  patchwise_contrastive_starting_epoch: ...
  patchwise_contrastive_type: ...
  patchwise_contrastive_time_window: ...
  patchwise_contrastive_patch_size: ...
  patchwise_contrastive_alpha: ...
  use_emd: false
  emd_sum_scale: 1.0
  re_sample: false
  re_sample_scale: 0.02

validation:
  steps: -1
  freq: 5
  batch_size: 8
  save_video: true

evaluation:
  steps: -1

device: cuda:0
multi_gpu: false
log_dir: "results/ulosd_human36m_new_128pix"
warm_start: false
warm_start_checkpoint: ''
warm_start_config: ''